version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: migration_db
    networks:
      - migration_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: flaskmig
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_server
    networks:
      - migration_net
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]

  web:
    build: .
    container_name: migration_app
    networks:
      - migration_net
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

volumes:
  pgdata:

networks:
  migration_net:
    driver: bridge
