version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: migration_db
    networks:
      - migration_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: flaskmig
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: migration_app
    networks:
      - migration_net
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1234@migration_db:5432/flaskmig
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:

networks:
  migration_net:
    driver: bridge
